# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: spree_store_d
  username: root
  password: farm
  pool: 5
  timeout: 5000